spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: cosmere
    show-sql: true
  flyway:
    enabled: true
    schemas: cosmere
    default-schema: cosmere
    create-schemas: true
    locations: classpath:db/migration
    repair-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0

server:
  port: 8081
